# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:49
from __future__ import unicode_literals

import appasista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=appasista.models.get_image_path)),
                ('unitcost', models.IntegerField()),
                ('fund_or_sell', models.CharField(choices=[('fund', 'Fund'), ('sell', 'Sell')], max_length=25)),
                ('video_link', models.URLField(default=None)),
                ('manfac_id', models.IntegerField()),
            ],
        ),
    ]
