# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appasista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video_link',
            new_name='video_url',
        ),
    ]
